-- ============================================================
-- RETROID POCKET 5 — Migration v6
-- IGDB metadata genisletme paketi
-- Supabase SQL Editor'de tumunu sec + Run
-- ============================================================

-- 1. games tablosuna daha zengin IGDB metadata alanlari ekle
ALTER TABLE public.games
  ADD COLUMN IF NOT EXISTS storyline TEXT,
  ADD COLUMN IF NOT EXISTS publisher TEXT,
  ADD COLUMN IF NOT EXISTS igdb_url TEXT,
  ADD COLUMN IF NOT EXISTS igdb_rating NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS igdb_synced_at TIMESTAMPTZ;

-- 2. screenshot / video / website gibi coklu asset'ler icin genel tablo
CREATE TABLE IF NOT EXISTS public.game_media_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id UUID NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL CHECK (asset_type IN ('screenshot','video','website','store_link')),
  url TEXT NOT NULL,
  label TEXT,
  source TEXT DEFAULT 'IGDB',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_game_media_assets_game_id
  ON public.game_media_assets(game_id);

CREATE INDEX IF NOT EXISTS idx_game_media_assets_type
  ON public.game_media_assets(asset_type);

-- 3. v_games_full view'ine yeni temel alanlari da yansit
CREATE OR REPLACE VIEW public.v_games_full AS
SELECT
  g.id,
  g.title,
  g.release_year,
  g.play_status,
  g.rating,
  g.igdb_rating,
  g.is_coop,
  g.coop_notes,
  g.is_iconic,
  g.description,
  g.storyline,
  g.developer,
  g.publisher,
  g.igdb_url,
  g.play_notes,
  g.game_log,
  g.tier,
  g.play_order,
  g.external_id,
  g.primary_cover_url,
  s.name AS series_name,
  COALESCE(
    json_agg(DISTINCT jsonb_build_object('id', gnr.id, 'name', gnr.name))
    FILTER (WHERE gnr.id IS NOT NULL), '[]'
  ) AS genres,
  COALESCE(
    json_agg(DISTINCT jsonb_build_object(
      'id', gp.id,
      'system', sys.name,
      'emulator', emu.name,
      'performance', gp.performance,
      'performance_notes', gp.performance_notes,
      'cover_url', gp.cover_url,
      'rom_status', gp.rom_status,
      'region', gp.region,
      'folder_path', gp.folder_path,
      'rom_url', gp.rom_url
    )) FILTER (WHERE gp.id IS NOT NULL), '[]'
  ) AS platforms
FROM public.games g
LEFT JOIN public.series s          ON g.series_id = s.id
LEFT JOIN public.game_genres gg    ON gg.game_id = g.id
LEFT JOIN public.genres gnr        ON gnr.id = gg.genre_id
LEFT JOIN public.game_platforms gp ON gp.game_id = g.id
LEFT JOIN public.systems sys       ON sys.id = gp.system_id
LEFT JOIN public.emulators emu     ON emu.id = gp.emulator_id
GROUP BY g.id, s.name;

-- 4. Dogrulama
SELECT column_name
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'games'
  AND column_name IN ('storyline','publisher','igdb_url','igdb_rating','igdb_synced_at');

SELECT COUNT(*) AS media_asset_count FROM public.game_media_assets;
